### ISSUE TITLE
Library built with 3.1.6 does not run with 3.1.8

### ISSUE THREAD

**Issue by space88man** [ben-manes/caffeine#1265]
I have a dependency `mylib.jar` built for Spring Boot 3.1.2 (using caffeine 3.1.6)

    
    
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
      <version>3.1.6</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>jcache</artifactId>
      <version>3.1.6</version>
      <scope>provided</scope>
    </dependency>

When the application is upgraded to Spring Boot 3.1.4  (which provides caffeine 3.1.8) the application no longer runs due to this dependency:

    Caused by: java.lang.NoSuchMethodError: 'void com.github.benmanes.caffeine.jcache.configuration.CaffeineConfiguration.setExpiryPolicyFactory(javax.cache.configuration.Factory)'

Would this have been expected to work, i.e., compile with 3.1.6 but runtime environment provides 3.1.8?

Other information:
* if the application is built to use 3.1.6 (overriding the Spring Boot curated version) it works
* if `mylib.jar` is updated to use caffeine 3.1.8 then it works in an unmodified Spring Boot 3.1.4 environment

Code snippet:

```java
        <K, V> CaffeineConfiguration<K, V> buildCaffeineConfig() {
            CaffeineConfiguration<K, V> config = new CaffeineConfiguration<>();
            if (this.lifeSpan > 0)
                config.setExpiryPolicyFactory(ModifiedExpiryPolicy.factoryOf(this.duration()));
            if (this.createdLifeSpan > 0)
                config.setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(this.createdDuration()));

            return config;
        }
```

**Comment by ben-manes** [comment]
When the configuration was made [fluent](https://github.com/ben-manes/caffeine/commit/963ba6edb3be0500f361a8fa1f8e0d743d15a94d) is changed the binary signature, which Java is not very tolerant of. This seemed like a benign change because jsr107 defines the api, so only applications should ever consider using an implementation class. In that case it is source compatible so a recompilation is low impact.

regardless of the theory, since it’s been released there’s as much potential pain if reverted which would not be a source compatible change. So I think you’ll need to upgrade.
