### ISSUE TITLE
NoClassDefFoundError CacheWriter

### ISSUE THREAD

**Issue by Btjones711** [ben-manes/caffeine#753]
Caused by: java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/CacheWriter
	at com.github.benmanes.caffeine.jcache.CacheFactory.createCache(CacheFactory.java:89)
	at com.github.benmanes.caffeine.jcache.CacheManagerImpl.lambda$createCache$0(CacheManagerImpl.java:92)

This is happening whenever calling a constructor that creates a cache like so:
`cache = Caching.getCachingProvider().getCacheManager()
                .createCache("cacheName",
                new MutableConfiguration<String, ExampleConfigModel>()
                    .setReadThrough(true)
                    .setCacheLoaderFactory(new FactoryBuilder.SingletonFactory<>(cacheLoader))
                    .setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(Duration.TEN_MINUTES)));`

Any thoughts on what can be going wrong?
This is after an update to 3.1.1

**Comment by ben-manes** [comment]
CacheWriter was deprecated for removal in v2, and removed in v3. It looks like you have a mixture of dependencies (JCache on v2 with core on v3)?

**Comment by Btjones711** [comment]
Sorry about that just noticed that in CacheFactory's history. Let me look into that dependency mixture! Thanks!

**Comment by Btjones711** [comment]
Yep, I think that was it. In my pom jcache was not being specified in dependency management and was probably defaulting to v2 by some other dependency. Thanks for the very quick response and the help!!
